services:
  # === PostgreSQL ===
  postgres:
    image: postgres:16
    container_name: gamevault_postgres
    ports:
      - "12000:5432"
    environment:
      - TZ=Asia/Singapore
      - POSTGRES_DB=gamevault
      - POSTGRES_USER=gamevault_user
      - POSTGRES_PASSWORD=gamevault_pass
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - gamevault

  # === Redis ===
  redis:
    image: redis:alpine
    container_name: gamevault_redis
    ports:
      - "12003:6379"
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/data/:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - gamevault

#  # === Spring Boot Backend ===
#  backend:
#    build: .
#    container_name: gamevault_backend
#    depends_on:
#      - postgres
#      - redis
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    volumes:
#      - ./secrets:/app/secrets   # 挂载本地 secrets 目录到容器的 /app/secrets
#    networks:
#      - gamevault

networks:
  gamevault:
    driver: bridge
