server:
  port: 8080

rsa:
  private-key: "file:secrets/keys/rsa-private.pem"
  public-key:  "file:secrets/keys/rsa-public.pem"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: ${rsa.public-key}
  datasource:
    url: jdbc:postgresql://localhost:12000/gamevault
    username: gamevault_user
    password: gamevault_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  data:
    redis:
      host: localhost
      database: 0
      port: 12003
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

app:
  jwt:
    # Replace with ultra-long random string (at least 64 bytes)
    secret: "F3NfhRgpwaw0zWvhLtGnDOHmZomVtzpdt9Js-UkDjGJYTe49kZgKjWoeNCk7VdLU5l5F_eKk5k7nrYzKX8SwA"
    expiration-minutes: 120
