server:
  port: 8080

rsa:
  private-key: "file:secrets/keys/rsa-private.pem"
  public-key:  "file:secrets/keys/rsa-public.pem"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: ${rsa.public-key}
  datasource:
    url: jdbc:postgresql://localhost:5432/zycgamevaultdatabase
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app:
  jwt:
    # Replace with ultra-long random string (at least 64 bytes)
    secret: "F3NfhRgpwaw0zWvhLtGnDOHmZomVtzpdt9Js-UkDjGJYTe49kZgKjWoeNCk7VdLU5l5F_eKk5k7nrYzKX8SwA"
    expiration-minutes: 120
